// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkeixtciawytirzjhydv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZWl4dGNpYXd5dGlyempoeWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDQxMjMsImV4cCI6MjA2OTIyMDEyM30.3gA1fl8mBeVsMaIphqtwM7AwZsS4-A_c1aRSQqLSlFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});